// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckEnvVar(arg1) {
  return window['go']['main']['App']['CheckEnvVar'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CreateProvider(arg1) {
  return window['go']['main']['App']['CreateProvider'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function ExecuteLaunchPi(arg1, arg2) {
  return window['go']['main']['App']['ExecuteLaunchPi'](arg1, arg2);
}

export function FetchModels(arg1) {
  return window['go']['main']['App']['FetchModels'](arg1);
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetWSLDetection() {
  return window['go']['main']['App']['GetWSLDetection']();
}

export function ImportModels(arg1, arg2) {
  return window['go']['main']['App']['ImportModels'](arg1, arg2);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function LaunchPi(arg1, arg2) {
  return window['go']['main']['App']['LaunchPi'](arg1, arg2);
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function MarkUpdateChecked() {
  return window['go']['main']['App']['MarkUpdateChecked']();
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function ReplaceModels(arg1, arg2) {
  return window['go']['main']['App']['ReplaceModels'](arg1, arg2);
}

export function SetDefaultModel(arg1, arg2) {
  return window['go']['main']['App']['SetDefaultModel'](arg1, arg2);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateProvider(arg1, arg2) {
  return window['go']['main']['App']['UpdateProvider'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
