// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';
import {provider} from '../models';
import {config} from '../models';
import {pi} from '../models';

export function CheckEnvVar(arg1:string):Promise<system.EnvCheckResult>;

export function CreateProvider(arg1:provider.Config):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function ExecuteLaunchPi(arg1:string,arg2:string):Promise<void>;

export function FetchModels(arg1:string):Promise<Array<provider.ModelInfo>>;

export function GetAppState():Promise<config.AppState>;

export function ImportModels(arg1:string,arg2:Array<provider.ModelInfo>):Promise<void>;

export function LaunchPi(arg1:string,arg2:string):Promise<pi.LaunchPreview>;

export function ListProviders():Promise<Array<provider.Config>>;

export function OpenConfigFolder():Promise<void>;

export function SetDefaultModel(arg1:string,arg2:string):Promise<void>;

export function TestConnection(arg1:string):Promise<provider.ConnectionTestResult>;

export function UpdateProvider(arg1:string,arg2:provider.Config):Promise<void>;

export function UpdateSettings(arg1:config.AppSettings):Promise<void>;
