// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';
import {updater} from '../models';
import {provider} from '../models';
import {config} from '../models';
import {wsl} from '../models';
import {pi} from '../models';

export function CheckEnvVar(arg1:string):Promise<system.EnvCheckResult>;

export function CheckForUpdate():Promise<updater.CheckResult>;

export function CreateProvider(arg1:provider.ConfigTransport):Promise<provider.ConfigTransport>;

export function DeleteProvider(arg1:string):Promise<void>;

export function ExecuteLaunchPi(arg1:string,arg2:string):Promise<void>;

export function FetchModels(arg1:string):Promise<Array<provider.ModelTransport>>;

export function GetAppState():Promise<config.AppState>;

export function GetWSLDetection():Promise<wsl.Detection>;

export function GetWSLPiConfigDocuments(arg1:string):Promise<wsl.PiConfigDocuments>;

export function GetWSLPiDetection(arg1:string):Promise<wsl.PiDetection>;

export function ImportModels(arg1:string,arg2:Array<provider.ModelTransport>):Promise<void>;

export function InstallUpdate():Promise<void>;

export function LaunchPi(arg1:string,arg2:string):Promise<pi.LaunchPreview>;

export function ListProviders():Promise<Array<provider.ConfigTransport>>;

export function MarkUpdateChecked():Promise<void>;

export function OpenConfigFolder():Promise<void>;

export function ReplaceModels(arg1:string,arg2:Array<provider.ModelTransport>,arg3:string):Promise<provider.ModelListTransport>;

export function SetDefaultModel(arg1:string,arg2:string):Promise<void>;

export function TestConnection(arg1:string):Promise<provider.ConnectionTestResult>;

export function UpdateProvider(arg1:string,arg2:provider.ConfigTransport):Promise<void>;

export function UpdateSettings(arg1:config.AppSettings):Promise<void>;
